/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v8.0
processor: MKV58F1M0xxx24
package_id: MKV58F1M0VLQ24
mcu_data: ksdk2_0
processor_version: 8.0.1
functionalGroups:
- name: RTEPIP_Basic
  UUID: addbdd22-a9df-4c2e-94b2-a872291934ea
  selectedCore: core0
- name: RTEPIP_Analog
  UUID: eaa2ad1a-4aac-45aa-9d4a-467bb39775c9
  selectedCore: core0
- name: RTEPIP_Digital
  UUID: affcf65a-f9f9-42cb-b7c2-5231045f239f
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * RTEPIP_Basic functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_6d0dd4e17e2f179c7d42d98767129ede'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'DMA'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - enableRoundRobinArbitration: 'false'
      - enableDebugMode: 'false'
    - dma_table: []
    - edma_channels: []
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_Error_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

static void DMA_init(void) {
}

/***********************************************************************************************************************
 * GPIOA initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOA'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_5920c5e026e8e974e6dc54fbd5e22ad7'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'GPIOA'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'PORTA_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '4'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOA_init(void) {
  /* Make sure, the clock gate for port A is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector PORTA_IRQn priority settings in the NVIC */
  NVIC_SetPriority(PORTA_IRQn, GPIOA_IRQ_PRIORITY);
  /* Enable interrupt PORTA_IRQn request in the NVIC */
  EnableIRQ(PORTA_IRQn);
}

/***********************************************************************************************************************
 * GPIOB initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOB'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_5920c5e026e8e974e6dc54fbd5e22ad7'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'GPIOB'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'PORTB_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '4'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOB_init(void) {
  /* Make sure, the clock gate for port B is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector PORTB_IRQn priority settings in the NVIC */
  NVIC_SetPriority(PORTB_IRQn, GPIOB_IRQ_PRIORITY);
  /* Enable interrupt PORTB_IRQn request in the NVIC */
  EnableIRQ(PORTB_IRQn);
}

/***********************************************************************************************************************
 * GPIOC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOC'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_5920c5e026e8e974e6dc54fbd5e22ad7'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'GPIOC'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'PORTC_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '4'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOC_init(void) {
  /* Make sure, the clock gate for port C is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector PORTC_IRQn priority settings in the NVIC */
  NVIC_SetPriority(PORTC_IRQn, GPIOC_IRQ_PRIORITY);
  /* Enable interrupt PORTC_IRQn request in the NVIC */
  EnableIRQ(PORTC_IRQn);
}

/***********************************************************************************************************************
 * GPIOD initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOD'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_5920c5e026e8e974e6dc54fbd5e22ad7'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'GPIOD'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'PORTD_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '4'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOD_init(void) {
  /* Make sure, the clock gate for port D is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector PORTD_IRQn priority settings in the NVIC */
  NVIC_SetPriority(PORTD_IRQn, GPIOD_IRQ_PRIORITY);
  /* Enable interrupt PORTD_IRQn request in the NVIC */
  EnableIRQ(PORTD_IRQn);
}

/***********************************************************************************************************************
 * GPIOE initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIOE'
- type: 'gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_5920c5e026e8e974e6dc54fbd5e22ad7'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'GPIOE'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'PORTE_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '4'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIOE_init(void) {
  /* Make sure, the clock gate for port E is enabled (e. g. in pin_mux.c) */
  /* Interrupt vector PORTE_IRQn priority settings in the NVIC */
  NVIC_SetPriority(PORTE_IRQn, GPIOE_IRQ_PRIORITY);
  /* Enable interrupt PORTE_IRQn request in the NVIC */
  EnableIRQ(PORTE_IRQn);
}

/***********************************************************************************************************************
 * PITMGR_LPTMR0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PITMGR_LPTMR0'
- type: 'lptmr'
- mode: 'LPTMR_GENERAL'
- custom_name_enabled: 'true'
- type_id: 'lptmr_48552e76e8733b28a9c768b6d8d4fefa'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'LPTMR0'
- config_sets:
  - fsl_lptmr:
    - lptmr_config:
      - timerMode: 'kLPTMR_TimerModeTimeCounter'
      - pinSelect: 'ALT.0'
      - pinPolarity: 'kLPTMR_PinPolarityActiveHigh'
      - enableFreeRunning: 'false'
      - bypassPrescaler: 'true'
      - prescalerClockSource: 'kLPTMR_PrescalerClock_3'
      - clockSource: 'RTECLK_HsRun240'
      - value: 'kLPTMR_Prescale_Glitch_0'
      - timerPeriod: '1ms'
    - enableInterrupt: 'true'
    - interrupt:
      - IRQn: 'LPTMR0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '6'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lptmr_config_t PITMGR_LPTMR0_config = {
  .timerMode = kLPTMR_TimerModeTimeCounter,
  .pinSelect = kLPTMR_PinSelectInput_0,
  .pinPolarity = kLPTMR_PinPolarityActiveHigh,
  .enableFreeRunning = false,
  .bypassPrescaler = true,
  .prescalerClockSource = kLPTMR_PrescalerClock_3,
  .value = kLPTMR_Prescale_Glitch_0
};

static void PITMGR_LPTMR0_init(void) {
  /* Initialize the LPTMR */
  LPTMR_Init(PITMGR_LPTMR0_PERIPHERAL, &PITMGR_LPTMR0_config);
  /* Set LPTMR period */
  LPTMR_SetTimerPeriod(PITMGR_LPTMR0_PERIPHERAL, PITMGR_LPTMR0_TICKS);
  /* Configure timer interrupt */
  LPTMR_EnableInterrupts(PITMGR_LPTMR0_PERIPHERAL, kLPTMR_TimerInterruptEnable);
  /* Interrupt vector LPTMR0_IRQn priority settings in the NVIC */
  NVIC_SetPriority(LPTMR0_IRQn, PITMGR_LPTMR0_IRQ_PRIORITY);
  /* Enable interrupt LPTMR0_IRQn request in the NVIC */
  EnableIRQ(LPTMR0_IRQn);
}

/***********************************************************************************************************************
 * TRNG0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TRNG0'
- type: 'TRNG'
- mode: 'General'
- custom_name_enabled: 'false'
- type_id: 'trng_dd5b2a6f14d45ca091cf6c9a38560d5e'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'TRNG0'
- config_sets:
  - fsl_trng:
    - settings_trng_config_t:
      - clockMode: 'kTRNG_ClockModeSystem'
      - struct_ring_oscillator:
        - ringOscDiv: 'kTRNG_RingOscDiv0'
        - sampleMode: 'kTRNG_SampleModeRaw'
      - entropyDelay: '3200'
      - sampleSize: '2500'
      - sparseBitLimit: '63'
      - retryCount: '1'
      - lock: 'false'
      - struct_statistical_checks:
        - longRunMaxLimit: '34'
        - monobitLimit:
          - maximum: '1384'
          - minimum: '1116'
        - runBit1Limit:
          - maximum: '405'
          - minimum: '227'
        - runBit2Limit:
          - maximum: '220'
          - minimum: '98'
        - runBit3Limit:
          - maximum: '125'
          - minimum: '37'
        - runBit4Limit:
          - maximum: '75'
          - minimum: '11'
        - runBit5Limit:
          - maximum: '47'
          - minimum: '1'
        - runBit6PlusLimit:
          - maximum: '47'
          - minimum: '1'
        - pokerLimit:
          - maximum: '26912'
          - minimum: '24445'
        - frequencyCountLimit:
          - maximum: '25600'
          - minimum: '1600'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const trng_config_t TRNG0_config = {
  .lock = false,
  .clockMode = kTRNG_ClockModeSystem,
  .ringOscDiv = kTRNG_RingOscDiv0,
  .sampleMode = kTRNG_SampleModeRaw,
  .entropyDelay = 3200,
  .sampleSize = 2500,
  .sparseBitLimit = 63,
  .retryCount = 1,
  .longRunMaxLimit = 34,
  .monobitLimit = {
    .maximum = 1384,
    .minimum = 1116
  },
  .runBit1Limit = {
    .maximum = 405,
    .minimum = 227
  },
  .runBit2Limit = {
    .maximum = 220,
    .minimum = 98
  },
  .runBit3Limit = {
    .maximum = 125,
    .minimum = 37
  },
  .runBit4Limit = {
    .maximum = 75,
    .minimum = 11
  },
  .runBit5Limit = {
    .maximum = 47,
    .minimum = 1
  },
  .runBit6PlusLimit = {
    .maximum = 47,
    .minimum = 1
  },
  .pokerLimit = {
    .maximum = 26912,
    .minimum = 24445
  },
  .frequencyCountLimit = {
    .maximum = 25600,
    .minimum = 1600
  }
};

static void TRNG0_init(void) {
  /* Initialize TRNG. */
  TRNG_Init(TRNG0_PERIPHERAL, &TRNG0_config);
}

/***********************************************************************************************************************
 * PIT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PIT'
- type: 'pit'
- mode: 'LPTMR_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'pit_a4782ba5223c8a2527ba91aeb2bc4159'
- functional_group: 'RTEPIP_Basic'
- peripheral: 'PIT'
- config_sets:
  - fsl_pit:
    - enableRunInDebug: 'false'
    - timingConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'RTECLK_HsRun240'
    - channels: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const pit_config_t PIT_config = {
  .enableRunInDebug = false
};

static void PIT_init(void) {
  /* Initialize the PIT. */
  PIT_Init(PIT_PERIPHERAL, &PIT_config);
}

/***********************************************************************************************************************
 * RTEPIP_Analog functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * EMAG_HSADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'EMAG_HSADC0'
- type: 'hsadc'
- mode: 'HSADC'
- custom_name_enabled: 'true'
- type_id: 'hsadc_5b2fece541907a1cbb07075efd51862d'
- functional_group: 'RTEPIP_Analog'
- peripheral: 'HSADC0'
- config_sets:
  - fsl_hsadc:
    - hsadcConfig:
      - dualConverterScanMode: 'kHSADC_DualConverterWorkAsTriggeredParallel'
      - enableSimultaneousMode: 'true'
      - resolution: 'kHSADC_Resolution12Bit'
      - DMATriggerSoruce: 'kHSADC_DMATriggerSourceAsEndOfScan'
      - idleWorkMode: 'kHSADC_IdleKeepNormal'
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'RTECLK_HsRun240'
      - powerUpDelayCount: '63'
    - hsadcConverterConfig:
      - clockDivisor: '2'
      - samplingTimeCount: '0'
      - calibrationMode: 'kHSADC_CalibrationModeSingleEnded'
      - enableConverters: 'kHSADC_ConverterA kHSADC_ConverterB'
    - channels_config_A_parallel:
      - 0:
        - sampleName: 'Sample_0'
        - channelNumberEnum: 'ADCA.CH0'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
      - 1:
        - sampleName: 'Sample_1'
        - channelNumberEnum: 'ADCA.CH1'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
      - 2:
        - sampleName: 'Sample_2'
        - channelNumberEnum: 'ADCA.CH6'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
      - 3:
        - sampleName: 'Sample_3'
        - channelNumberEnum: 'ADCA.CH7'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
      - 4:
        - sampleName: 'Sample_4'
        - channelNumberEnum: 'ADCA.CH8'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
      - 5:
        - sampleName: 'Sample_5'
        - channelNumberEnum: 'ADCA.CH9'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
    - channels_config_B_parallel:
      - 0:
        - sampleName: 'Sample_8'
        - channelNumberEnum: 'ADCB.CH0'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
      - 1:
        - sampleName: 'Sample_9'
        - channelNumberEnum: 'ADCB.CH1'
        - enableDifferentialPair: 'false'
        - zeroCrossingMode: 'kHSADC_ZeroCorssingDisabled'
        - highLimitValue: '32760'
        - lowLimitValue: '0'
        - offsetValue: '0'
        - enableWaitSync: 'false'
        - enableSampleInterrupt: 'false'
    - interrupt:
      - interruptSources: ''
      - enable_err_irq: 'false'
      - interrupt_err:
        - IRQn: 'HSADC_ERR_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_cc0_irq: 'false'
      - interrupt_cc0:
        - IRQn: 'HSADC0_CCA_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_cc1_irq: 'false'
      - interrupt_cc1:
        - IRQn: 'HSADC0_CCB_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const hsadc_config_t EMAG_HSADC0_config = {
  .dualConverterScanMode = kHSADC_DualConverterWorkAsTriggeredParallel,
  .enableSimultaneousMode = true,
  .resolution = kHSADC_Resolution12Bit,
  .DMATriggerSoruce = kHSADC_DMATriggerSourceAsEndOfScan,
  .idleWorkMode = kHSADC_IdleKeepNormal,
  .powerUpDelayCount = 63
};
const hsadc_converter_config_t EMAG_HSADC0_converter_config = {
  .clockDivisor = 2,
  .samplingTimeCount = 0,
  .powerUpCalibrationModeMask = kHSADC_CalibrationModeSingleEnded
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_0 = {
  .channelNumber = 0,
  .channel67MuxNumber = 0,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_1 = {
  .channelNumber = 1,
  .channel67MuxNumber = 0,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_2 = {
  .channelNumber = 6,
  .channel67MuxNumber = 0,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_3 = {
  .channelNumber = 7,
  .channel67MuxNumber = 0,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_4 = {
  .channelNumber = 6,
  .channel67MuxNumber = 1,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_5 = {
  .channelNumber = 7,
  .channel67MuxNumber = 1,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_8 = {
  .channelNumber = 0,
  .channel67MuxNumber = 0,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};
const hsadc_sample_config_t EMAG_HSADC0_config_Sample_9 = {
  .channelNumber = 1,
  .channel67MuxNumber = 0,
  .enableDifferentialPair = false,
  .zeroCrossingMode = kHSADC_ZeroCorssingDisabled,
  .highLimitValue = 32760,
  .lowLimitValue = 0,
  .offsetValue = 0,
  .enableWaitSync = false
};

static void EMAG_HSADC0_init(void) {
  /* HSADC initialization */
  HSADC_Init(EMAG_HSADC0_PERIPHERAL, &EMAG_HSADC0_config);
  /* Configure each converter */
  HSADC_SetConverterConfig(EMAG_HSADC0_PERIPHERAL, (kHSADC_ConverterA | kHSADC_ConverterB), &EMAG_HSADC0_converter_config);
  /* Enable power for each converter */
  HSADC_EnableConverterPower(EMAG_HSADC0_PERIPHERAL, (kHSADC_ConverterA | kHSADC_ConverterB), true);
  /* Make each converter exit stop mode */
  HSADC_EnableConverter(EMAG_HSADC0_PERIPHERAL, (kHSADC_ConverterA | kHSADC_ConverterB), true);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 0U, &EMAG_HSADC0_config_Sample_0);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 1U, &EMAG_HSADC0_config_Sample_1);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 2U, &EMAG_HSADC0_config_Sample_2);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 3U, &EMAG_HSADC0_config_Sample_3);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 4U, &EMAG_HSADC0_config_Sample_4);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 5U, &EMAG_HSADC0_config_Sample_5);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 8U, &EMAG_HSADC0_config_Sample_8);
  /* Configure the samples. */
  HSADC_SetSampleConfig(EMAG_HSADC0_PERIPHERAL, 9U, &EMAG_HSADC0_config_Sample_9);
  /* Enable samples. */
  HSADC_EnableSample(EMAG_HSADC0_PERIPHERAL, 0x33FU, true);
}

/***********************************************************************************************************************
 * RTEPIP_Digital functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DBG_UART initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DBG_UART'
- type: 'uart'
- mode: 'transfer'
- custom_name_enabled: 'true'
- type_id: 'uart_88ab1eca0cddb7ee407685775de016d5'
- functional_group: 'RTEPIP_Digital'
- peripheral: 'UART0'
- config_sets:
  - uartConfig_t:
    - uartConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'GetFreq'
      - baudRate_Bps: '1152000'
      - parityMode: 'kUART_ParityDisabled'
      - stopBitCount: 'kUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - idleType: 'kUART_IdleTypeStartBit'
      - enableTx: 'true'
      - enableRx: 'true'
  - transferCfg:
    - transfer:
      - init_rx_transfer: 'true'
      - rx_transfer:
        - data_size: '256'
      - init_tx_transfer: 'true'
      - tx_transfer:
        - data_size: '256'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const uart_config_t DBG_UART_config = {
  .baudRate_Bps = 1152000,
  .parityMode = kUART_ParityDisabled,
  .stopBitCount = kUART_OneStopBit,
  .txFifoWatermark = 0,
  .rxFifoWatermark = 1,
  .idleType = kUART_IdleTypeStartBit,
  .enableTx = true,
  .enableRx = true
};
uart_handle_t DBG_UART_handle;
uint8_t DBG_UART_rxBuffer[DBG_UART_RX_BUFFER_SIZE];
const uart_transfer_t DBG_UART_rxTransfer = {
  .data = DBG_UART_rxBuffer,
  .dataSize = DBG_UART_RX_BUFFER_SIZE
};
uint8_t DBG_UART_txBuffer[DBG_UART_TX_BUFFER_SIZE];
const uart_transfer_t DBG_UART_txTransfer = {
  .data = DBG_UART_txBuffer,
  .dataSize = DBG_UART_TX_BUFFER_SIZE
};

static void DBG_UART_init(void) {
  UART_Init(DBG_UART_PERIPHERAL, &DBG_UART_config, DBG_UART_CLOCK_SOURCE);
  UART_TransferCreateHandle(DBG_UART_PERIPHERAL, &DBG_UART_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * IMC_UART initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'IMC_UART'
- type: 'uart'
- mode: 'transfer'
- custom_name_enabled: 'true'
- type_id: 'uart_88ab1eca0cddb7ee407685775de016d5'
- functional_group: 'RTEPIP_Digital'
- peripheral: 'UART1'
- config_sets:
  - uartConfig_t:
    - uartConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'GetFreq'
      - baudRate_Bps: '1152000'
      - parityMode: 'kUART_ParityDisabled'
      - stopBitCount: 'kUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - idleType: 'kUART_IdleTypeStartBit'
      - enableTx: 'true'
      - enableRx: 'true'
  - transferCfg:
    - transfer:
      - init_rx_transfer: 'true'
      - rx_transfer:
        - data_size: '1024'
      - init_tx_transfer: 'true'
      - tx_transfer:
        - data_size: '1024'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const uart_config_t IMC_UART_config = {
  .baudRate_Bps = 1152000,
  .parityMode = kUART_ParityDisabled,
  .stopBitCount = kUART_OneStopBit,
  .txFifoWatermark = 0,
  .rxFifoWatermark = 1,
  .idleType = kUART_IdleTypeStartBit,
  .enableTx = true,
  .enableRx = true
};
uart_handle_t IMC_UART_handle;
uint8_t IMC_UART_rxBuffer[IMC_UART_RX_BUFFER_SIZE];
const uart_transfer_t IMC_UART_rxTransfer = {
  .data = IMC_UART_rxBuffer,
  .dataSize = IMC_UART_RX_BUFFER_SIZE
};
uint8_t IMC_UART_txBuffer[IMC_UART_TX_BUFFER_SIZE];
const uart_transfer_t IMC_UART_txTransfer = {
  .data = IMC_UART_txBuffer,
  .dataSize = IMC_UART_TX_BUFFER_SIZE
};

static void IMC_UART_init(void) {
  UART_Init(IMC_UART_PERIPHERAL, &IMC_UART_config, IMC_UART_CLOCK_SOURCE);
  UART_TransferCreateHandle(IMC_UART_PERIPHERAL, &IMC_UART_handle, NULL, NULL);
}

/***********************************************************************************************************************
 * TOF_I2C initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TOF_I2C'
- type: 'i2c'
- mode: 'I2C_Polling'
- custom_name_enabled: 'true'
- type_id: 'i2c_2566d7363e7e9aaedabb432110e372d7'
- functional_group: 'RTEPIP_Digital'
- peripheral: 'I2C1'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'GetFreq'
    - i2c_master_config:
      - enableMaster: 'true'
      - enableStopHold: 'false'
      - baudRate_Bps: '400000'
      - glitchFilterWidth: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t TOF_I2C_config = {
  .enableMaster = true,
  .enableStopHold = false,
  .baudRate_Bps = 400000,
  .glitchFilterWidth = 0
};

static void TOF_I2C_init(void) {
  /* Initialization function */
  I2C_MasterInit(TOF_I2C_PERIPHERAL, &TOF_I2C_config, TOF_I2C_CLK_FREQ);
}

/***********************************************************************************************************************
 * IMU_TCS_I2C initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'IMU_TCS_I2C'
- type: 'i2c'
- mode: 'I2C_Polling'
- custom_name_enabled: 'true'
- type_id: 'i2c_2566d7363e7e9aaedabb432110e372d7'
- functional_group: 'RTEPIP_Digital'
- peripheral: 'I2C0'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'GetFreq'
    - i2c_master_config:
      - enableMaster: 'true'
      - enableStopHold: 'false'
      - baudRate_Bps: '400000'
      - glitchFilterWidth: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t IMU_TCS_I2C_config = {
  .enableMaster = true,
  .enableStopHold = false,
  .baudRate_Bps = 400000,
  .glitchFilterWidth = 0
};

static void IMU_TCS_I2C_init(void) {
  /* Initialization function */
  I2C_MasterInit(IMU_TCS_I2C_PERIPHERAL, &IMU_TCS_I2C_config, IMU_TCS_I2C_CLK_FREQ);
}

/***********************************************************************************************************************
 * CLED_FTM3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CLED_FTM3'
- type: 'ftm'
- mode: 'CenterAligned'
- custom_name_enabled: 'true'
- type_id: 'ftm_04a15ae4af2b404bf2ae403c3dbe98b3'
- functional_group: 'RTEPIP_Digital'
- peripheral: 'FTM3'
- config_sets:
  - ftm_main_config:
    - ftm_config:
      - clockSource: 'kFTM_FixedClock'
      - clockSourceFreq: 'GetFreq'
      - prescale: 'kFTM_Prescale_Divide_1'
      - timerFrequency: '1000'
      - bdmMode: 'kFTM_BdmMode_0'
      - pwmSyncMode: 'kFTM_SoftwareTrigger'
      - reloadPoints: ''
      - faultMode: 'kFTM_Fault_Disable'
      - faultFilterValue: '0'
      - deadTimePrescale: 'kFTM_Deadtime_Prescale_1'
      - deadTimeValue: '0'
      - extTriggers: ''
      - chnlInitState: ''
      - chnlPolarity: ''
      - useGlobalTimeBase: 'false'
    - timer_interrupts: ''
    - enable_irq: 'false'
    - ftm_interrupt:
      - IRQn: 'FTM3_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'true'
  - ftm_center_aligned_mode:
    - ftm_center_aligned_channels_config:
      - 0:
        - chnlNumber: 'kFTM_Chnl_0'
        - level: 'kFTM_LowTrue'
        - dutyCyclePercent: '0'
        - enable_chan_irq: 'false'
      - 1:
        - chnlNumber: 'kFTM_Chnl_1'
        - level: 'kFTM_LowTrue'
        - dutyCyclePercent: '0'
        - enable_chan_irq: 'false'
      - 2:
        - chnlNumber: 'kFTM_Chnl_2'
        - level: 'kFTM_LowTrue'
        - dutyCyclePercent: '0'
        - enable_chan_irq: 'false'
      - 3:
        - chnlNumber: 'kFTM_Chnl_3'
        - level: 'kFTM_LowTrue'
        - dutyCyclePercent: '0'
        - enable_chan_irq: 'false'
      - 4:
        - chnlNumber: 'kFTM_Chnl_4'
        - level: 'kFTM_LowTrue'
        - dutyCyclePercent: '0'
        - enable_chan_irq: 'false'
      - 5:
        - chnlNumber: 'kFTM_Chnl_5'
        - level: 'kFTM_LowTrue'
        - dutyCyclePercent: '0'
        - enable_chan_irq: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ftm_config_t CLED_FTM3_config = {
  .prescale = kFTM_Prescale_Divide_1,
  .bdmMode = kFTM_BdmMode_0,
  .pwmSyncMode = kFTM_SoftwareTrigger,
  .reloadPoints = 0,
  .faultMode = kFTM_Fault_Disable,
  .faultFilterValue = 0,
  .deadTimePrescale = kFTM_Deadtime_Prescale_1,
  .deadTimeValue = 0,
  .extTriggers = 0,
  .chnlInitState = 0,
  .chnlPolarity = 0,
  .useGlobalTimeBase = false
};
const ftm_chnl_pwm_signal_param_t CLED_FTM3_centerPwmSignalParams[] = { 
  {
    .chnlNumber = kFTM_Chnl_0,
    .level = kFTM_LowTrue,
    .dutyCyclePercent = 0
  },
  {
    .chnlNumber = kFTM_Chnl_1,
    .level = kFTM_LowTrue,
    .dutyCyclePercent = 0
  },
  {
    .chnlNumber = kFTM_Chnl_2,
    .level = kFTM_LowTrue,
    .dutyCyclePercent = 0
  },
  {
    .chnlNumber = kFTM_Chnl_3,
    .level = kFTM_LowTrue,
    .dutyCyclePercent = 0
  },
  {
    .chnlNumber = kFTM_Chnl_4,
    .level = kFTM_LowTrue,
    .dutyCyclePercent = 0
  },
  {
    .chnlNumber = kFTM_Chnl_5,
    .level = kFTM_LowTrue,
    .dutyCyclePercent = 0
  }
};

static void CLED_FTM3_init(void) {
  FTM_Init(CLED_FTM3_PERIPHERAL, &CLED_FTM3_config);
  FTM_SetupPwm(CLED_FTM3_PERIPHERAL, CLED_FTM3_centerPwmSignalParams, sizeof(CLED_FTM3_centerPwmSignalParams) / sizeof(ftm_chnl_pwm_signal_param_t), kFTM_CenterAlignedPwm, 1000U, CLED_FTM3_CLOCK_SOURCE);
  FTM_StartTimer(CLED_FTM3_PERIPHERAL, kFTM_FixedClock);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void RTEPIP_Basic(void)
{
  /* Global initialization */
  DMAMUX_Init(DMA_DMAMUX_BASEADDR);
  EDMA_Init(DMA_DMA_BASEADDR, &DMA_config);

  /* Initialize components */
  DMA_init();
  GPIOA_init();
  GPIOB_init();
  GPIOC_init();
  GPIOD_init();
  GPIOE_init();
  PITMGR_LPTMR0_init();
  TRNG0_init();
  PIT_init();
}

void RTEPIP_Analog(void)
{
  /* Initialize components */
  EMAG_HSADC0_init();
}

void RTEPIP_Digital(void)
{
  /* Initialize components */
  //DBG_UART_init();
  IMC_UART_init();
  TOF_I2C_init();
  IMU_TCS_I2C_init();
  CLED_FTM3_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
}
