/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MKV58F1M0xxx24
package_id: MKV58F1M0VLQ24
mcu_data: ksdk2_0
processor_version: 8.0.1
pin_labels:
- {pin_num: '1', pin_signal: HSADC0B_CH16/HSADC1A_CH0/PTE0/SPI1_PCS1/UART1_TX/XB_OUT10/XB_IN11/I2C1_SDA/TRACE_CLKOUT, label: IMC_UART_TX, identifier: IMC_UART_TX}
- {pin_num: '2', pin_signal: HSADC0B_CH17/HSADC1A_CH1/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/XB_OUT11/XB_IN7/I2C1_SCL/TRACE_D3, label: IMC_UART_RX, identifier: IMC_UART_RX}
- {pin_num: '8', pin_signal: HSADC1A_CH5/ADC0_SE10/ADC0_DM2/PTE5/SPI1_PCS2/UART3_RX/FLEXPWM1_A0/FTM3_CH0, label: CLED_LR, identifier: CLED_LR}
- {pin_num: '9', pin_signal: HSADC1B_CH7/ADC0_SE4a/PTE6/LLWU_P16/SPI1_PCS3/UART3_CTS_b/FLEXPWM1_B0/FTM3_CH1, label: CLED_LG, identifier: CLED_LG}
- {pin_num: '10', pin_signal: PTE7/UART3_RTS_b/FLEXPWM1_A1/FTM3_CH2, label: CLED_LB, identifier: CLED_LB}
- {pin_num: '11', pin_signal: PTE8/UART5_TX/FLEXPWM1_B1/FTM3_CH3, label: CLED_RR, identifier: CLED_RR}
- {pin_num: '12', pin_signal: PTE9/LLWU_P17/UART5_RX/FLEXPWM1_A2/FTM3_CH4, label: CLED_RG, identifier: CLED_RG}
- {pin_num: '13', pin_signal: PTE10/LLWU_P18/UART5_CTS_b/FLEXPWM1_B2/FTM3_CH5, label: CLED_RB, identifier: CLED_RB}
- {pin_num: '18', pin_signal: HSADC0A_CH0/ADC0_SE1/ADC0_DP1/PTE16/SPI0_PCS0/UART2_TX/FTM_CLKIN0/FTM0_FLT3, label: EMAG_EWL, identifier: EMAG_EWL}
- {pin_num: '19', pin_signal: HSADC0A_CH1/ADC0_SE9/ADC0_DM1/PTE17/LLWU_P19/SPI0_SCK/UART2_RX/FTM_CLKIN1/LPTMR0_ALT3, label: EMAG_EXL, identifier: EMAG_EXL}
- {pin_num: '20', pin_signal: HSADC0B_CH0/ADC0_SE5a/PTE18/LLWU_P20/SPI0_SOUT/UART2_CTS_b/I2C0_SDA, label: EMAG_EWR, identifier: EMAG_EWR}
- {pin_num: '21', pin_signal: HSADC0B_CH1/ADC0_SE6a/PTE19/SPI0_SIN/UART2_RTS_b/I2C0_SCL/CMP3_OUT, label: EMAG_EXR, identifier: EMAG_EXR}
- {pin_num: '23', pin_signal: HSADC0A_CH6/ADC0_SE7a, label: EMAG_EYL, identifier: EMAG_EYL}
- {pin_num: '24', pin_signal: HSADC0A_CH7/ADC0_SE4b, label: EMAG_EZL, identifier: EMAG_EZL}
- {pin_num: '25', pin_signal: HSADC0A_CH8/ADC0_SE5b/PTE20/FTM1_CH0/UART0_TX/FTM1_QD_PHA, label: EMAG_EYR, identifier: EMAG_EYR}
- {pin_num: '26', pin_signal: HSADC0A_CH9/HSADC1A_CH7/PTE21/XB_IN9/FTM1_CH1/UART0_RX/FTM1_QD_PHB, label: EMAG_EZR, identifier: EMAG_EZR}
- {pin_num: '27', pin_signal: HSADC0A_CH2/HSADC1A_CH2, label: EMAG_EYLF, identifier: EMAG_EYLF}
- {pin_num: '28', pin_signal: HSADC0A_CH3/HSADC1A_CH3, label: EMAG_EZLF, identifier: EMAG_EZLF}
- {pin_num: '29', pin_signal: HSADC0A_CH10/HSADC1B_CH2, label: EMAG_EYRF, identifier: EMAG_EYRF}
- {pin_num: '30', pin_signal: HSADC0A_CH11/HSADC1B_CH3, label: EMAG_EZRF, identifier: EMAG_EZRF}
- {pin_num: '50', pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/XB_IN4/EWM_IN/JTAG_TCLK/SWD_CLK, label: DBG_TCK, identifier: DBG_TCK}
- {pin_num: '53', pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/XB_IN9/EWM_OUT_b/FLEXPWM0_A0/JTAG_TMS/SWD_DIO, label: DBT_TMS, identifier: DBT_TMS}
- {pin_num: '51', pin_signal: PTA1/UART0_RX/FTM0_CH6/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/JTAG_TDI, label: DBG_UART_RX, identifier: DBG_UART_RX}
- {pin_num: '52', pin_signal: PTA2/UART0_TX/FTM0_CH7/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0/JTAG_TDO/TRACE_SWO, label: DBG_UART_TX, identifier: DBG_UART_TX}
- {pin_num: '59', pin_signal: HSADC1B_CH8/PTA7/FTM0_CH4/RMII0_MDIO/MII0_MDIO/TRACE_D3, label: TOF0_XHT, identifier: TOF0_XHT}
- {pin_num: '60', pin_signal: HSADC1B_CH9/PTA8/FTM1_CH0/RMII0_MDC/MII0_MDC/TRACE_D2, label: TOF0_INT, identifier: TOF0_INT}
- {pin_num: '61', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/TRACE_D1, label: TOF1_XHT, identifier: TOF1_XHT}
- {pin_num: '62', pin_signal: PTA10/LLWU_P22/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0, label: TOF1_INT, identifier: TOF1_INT}
- {pin_num: '63', pin_signal: PTA11/LLWU_P23/FTM2_CH1/MII0_RXCLK/FTM2_QD_PHB/I2C0_SDA, label: TOF2_XHT, identifier: TOF2_XHT}
- {pin_num: '64', pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/FTM1_QD_PHA/I2C0_SCL, label: TOF2_INT, identifier: TOF2_INT}
- {pin_num: '65', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/FTM1_QD_PHB/I2C1_SDA, label: TOFn_SDA, identifier: TOFn_SDA}
- {pin_num: '66', pin_signal: CMP3_IN0/PTA14/SPI0_PCS0/UART0_TX/CAN2_TX/RMII0_CRS_DV/MII0_RXDV/I2C1_SCL, label: TOFn_SCL, identifier: TOFn_SCL}
- {pin_num: '79', pin_signal: PTA28/MII0_TXER/FB_A25, label: TCS_INT, identifier: TCS_INT}
- {pin_num: '80', pin_signal: PTA29/MII0_COL/FB_A24, label: IMU_INT, identifier: IMU_INT}
- {pin_num: '81', pin_signal: HSADC0B_CH2/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX/RMII0_MDIO/MII0_MDIO, label: IMU_SCL, identifier: IMU_SCL;TCS_SCL}
- {pin_num: '82', pin_signal: HSADC0B_CH3/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX/RMII0_MDC/MII0_MDC, label: IMU_SDA, identifier: IMU_SDA;TCS_SDA}
- {pin_num: '137', pin_signal: PTD8/LLWU_P24/I2C1_SCL/UART5_RX/FLEXPWM0_A3/FB_A16, label: KEY_SW07, identifier: KEY_SW07}
- {pin_num: '138', pin_signal: PTD9/I2C1_SDA/UART5_TX/FLEXPWM0_B3/FB_A17, label: KEY_SW, identifier: KEY_SW00}
- {pin_num: '139', pin_signal: PTD10/UART5_RTS_b/FLEXPWM0_A2/FB_A18, label: KEY_SW06, identifier: KEY_SW06}
- {pin_num: '140', pin_signal: PTD11/LLWU_P25/SPI2_PCS0/UART5_CTS_b/FLEXPWM0_B2/FB_A19, label: KEY_SW01, identifier: KEY_SW01}
- {pin_num: '141', pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/XB_IN5/XB_OUT5/FLEXPWM0_A1/FB_A20, label: KEY_SW05, identifier: KEY_SW05}
- {pin_num: '142', pin_signal: PTD13/SPI2_SOUT/XB_IN7/XB_OUT7/FLEXPWM0_B1/FB_A21, label: KEY_SW02, identifier: KEY_SW02}
- {pin_num: '143', pin_signal: PTD14/SPI2_SIN/XB_IN11/XB_OUT11/FLEXPWM0_A0/FB_A22, label: KEY_SW04, identifier: KEY_SW04}
- {pin_num: '144', pin_signal: PTD15/SPI2_PCS1/FLEXPWM0_B0/FB_A23, label: KEY_SW03, identifier: KEY_SW03}
- {pin_num: '119', pin_signal: PTC14/I2C1_SCL/I2C0_SCL/FLEXPWM1_A0/FB_AD25/UART4_RX, label: AUX_UART4_RX, identifier: AUX_UART4_RX}
- {pin_num: '120', pin_signal: PTC15/I2C1_SDA/I2C0_SDA/FLEXPWM1_B0/FB_AD24/UART4_TX, label: AUX_UART4_TX, identifier: AUX_UART4_TX}
- {pin_num: '123', pin_signal: PTC16/CAN1_RX/UART3_RX/ENET0_1588_TMR0/FLEXPWM1_A2/FB_CS5_b/FB_TSIZ1/FB_BE23_16_b, label: AUX_UART3_RX, identifier: AUX_UART3_RX}
- {pin_num: '124', pin_signal: PTC17/CAN1_TX/UART3_TX/ENET0_1588_TMR1/FLEXPWM1_B2/FB_CS4_b/FB_TSIZ0/FB_BE31_24_b, label: AUX_UART3_TX, identifier: AUX_UART3_TX}
- {pin_num: '129', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FTM0_CH2/FLEXPWM0_A1/I2C0_SCL/FB_AD4/FLEXPWM1_A1, label: AUX_UART2_RX, identifier: AUX_UART2_RX}
- {pin_num: '130', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FTM0_CH3/FLEXPWM0_B1/I2C0_SDA/FB_AD3/FLEXPWM1_B1, label: AUX_UART2_TX, identifier: AUX_UART2_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Basic:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '5', peripheral: PMC, signal: 'VDD, 5', pin_signal: VDD5}
  - {pin_num: '16', peripheral: PMC, signal: 'VDD, 16', pin_signal: VDD16}
  - {pin_num: '43', peripheral: PMC, signal: 'VDD, 44', pin_signal: VDD43}
  - {pin_num: '56', peripheral: PMC, signal: 'VDD, 57', pin_signal: VDD56}
  - {pin_num: '70', peripheral: PMC, signal: 'VDD, 71', pin_signal: VDD70}
  - {pin_num: '94', peripheral: PMC, signal: 'VDD, 95', pin_signal: VDD94}
  - {pin_num: '108', peripheral: PMC, signal: 'VDD, 109', pin_signal: VDD108}
  - {pin_num: '122', peripheral: PMC, signal: 'VDD, 123', pin_signal: VDD122}
  - {pin_num: '135', peripheral: PMC, signal: 'VDD, 136', pin_signal: VDD135}
  - {pin_num: '31', peripheral: PMC, signal: VDDA, pin_signal: VDDA}
  - {pin_num: '6', peripheral: PMC, signal: 'VSS, 6', pin_signal: VSS6}
  - {pin_num: '17', peripheral: PMC, signal: 'VSS, 17', pin_signal: VSS17}
  - {pin_num: '22', peripheral: PMC, signal: 'VSS, 22', pin_signal: VSS22}
  - {pin_num: '44', peripheral: PMC, signal: 'VSS, 45', pin_signal: VSS44}
  - {pin_num: '57', peripheral: PMC, signal: 'VSS, 58', pin_signal: VSS57}
  - {pin_num: '71', peripheral: PMC, signal: 'VSS, 72', pin_signal: VSS71}
  - {pin_num: '93', peripheral: PMC, signal: 'VSS, 94', pin_signal: VSS93}
  - {pin_num: '107', peripheral: PMC, signal: 'VSS, 108', pin_signal: VSS107}
  - {pin_num: '121', peripheral: PMC, signal: 'VSS, 122', pin_signal: VSS121}
  - {pin_num: '134', peripheral: PMC, signal: 'VSS, 135', pin_signal: VSS134}
  - {pin_num: '34', peripheral: PMC, signal: VSSA, pin_signal: VSSA}
  - {pin_num: '72', peripheral: OSC0, signal: EXTAL0, pin_signal: EXTAL0/PTA18/XB_IN7/FTM0_FLT2/FTM_CLKIN0/XB_OUT8/FTM3_CH2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Basic
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Basic(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);

    /* PORTA18 (pin 72) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_InterMcuComm:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: UART1, signal: TX, pin_signal: HSADC0B_CH16/HSADC1A_CH0/PTE0/SPI1_PCS1/UART1_TX/XB_OUT10/XB_IN11/I2C1_SDA/TRACE_CLKOUT, direction: OUTPUT,
    drive_strength: high, pull_select: up, pull_enable: enable}
  - {pin_num: '2', peripheral: UART1, signal: RX, pin_signal: HSADC0B_CH17/HSADC1A_CH1/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/XB_OUT11/XB_IN7/I2C1_SCL/TRACE_D3, drive_strength: high,
    pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_InterMcuComm
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_InterMcuComm(void)
{
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTE0 (pin 1) is configured as UART1_TX */
    PORT_SetPinMux(RTEPIN_INTERMCUCOMM_IMC_UART_TX_PORT, RTEPIN_INTERMCUCOMM_IMC_UART_TX_PIN, kPORT_MuxAlt3);

    PORTE->PCR[0] = ((PORTE->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTE1 (pin 2) is configured as UART1_RX */
    PORT_SetPinMux(RTEPIN_INTERMCUCOMM_IMC_UART_RX_PORT, RTEPIN_INTERMCUCOMM_IMC_UART_RX_PIN, kPORT_MuxAlt3);

    PORTE->PCR[1] = ((PORTE->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART1TXSRC_MASK | SIM_SOPT5_UART1RXSRC_MASK)))

                  /* UART 1 transmit data source select: UART1_TX pin. */
                  | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX)

                  /* UART 1 receive data source select: UART1_RX pin. */
                  | SIM_SOPT5_UART1RXSRC(SOPT5_UART1RXSRC_UART_RX));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_CLED:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '8', peripheral: FTM3, signal: 'CH, 0', pin_signal: HSADC1A_CH5/ADC0_SE10/ADC0_DM2/PTE5/SPI1_PCS2/UART3_RX/FLEXPWM1_A0/FTM3_CH0, direction: OUTPUT}
  - {pin_num: '9', peripheral: FTM3, signal: 'CH, 1', pin_signal: HSADC1B_CH7/ADC0_SE4a/PTE6/LLWU_P16/SPI1_PCS3/UART3_CTS_b/FLEXPWM1_B0/FTM3_CH1, direction: OUTPUT}
  - {pin_num: '10', peripheral: FTM3, signal: 'CH, 2', pin_signal: PTE7/UART3_RTS_b/FLEXPWM1_A1/FTM3_CH2, direction: OUTPUT}
  - {pin_num: '11', peripheral: FTM3, signal: 'CH, 3', pin_signal: PTE8/UART5_TX/FLEXPWM1_B1/FTM3_CH3, direction: OUTPUT}
  - {pin_num: '12', peripheral: FTM3, signal: 'CH, 4', pin_signal: PTE9/LLWU_P17/UART5_RX/FLEXPWM1_A2/FTM3_CH4, direction: OUTPUT}
  - {pin_num: '13', peripheral: FTM3, signal: 'CH, 5', pin_signal: PTE10/LLWU_P18/UART5_CTS_b/FLEXPWM1_B2/FTM3_CH5, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_CLED
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_CLED(void)
{
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTE10 (pin 13) is configured as FTM3_CH5 */
    PORT_SetPinMux(RTEPIN_CLED_CLED_RB_PORT, RTEPIN_CLED_CLED_RB_PIN, kPORT_MuxAlt6);

    /* PORTE5 (pin 8) is configured as FTM3_CH0 */
    PORT_SetPinMux(RTEPIN_CLED_CLED_LR_PORT, RTEPIN_CLED_CLED_LR_PIN, kPORT_MuxAlt6);

    /* PORTE6 (pin 9) is configured as FTM3_CH1 */
    PORT_SetPinMux(RTEPIN_CLED_CLED_LG_PORT, RTEPIN_CLED_CLED_LG_PIN, kPORT_MuxAlt6);

    /* PORTE7 (pin 10) is configured as FTM3_CH2 */
    PORT_SetPinMux(RTEPIN_CLED_CLED_LB_PORT, RTEPIN_CLED_CLED_LB_PIN, kPORT_MuxAlt6);

    /* PORTE8 (pin 11) is configured as FTM3_CH3 */
    PORT_SetPinMux(RTEPIN_CLED_CLED_RR_PORT, RTEPIN_CLED_CLED_RR_PIN, kPORT_MuxAlt6);

    /* PORTE9 (pin 12) is configured as FTM3_CH4 */
    PORT_SetPinMux(RTEPIN_CLED_CLED_RG_PORT, RTEPIN_CLED_CLED_RG_PIN, kPORT_MuxAlt6);

    SIM->SOPT8 =
        ((SIM->SOPT8 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT8_FTM3OCH0SRC_MASK | SIM_SOPT8_FTM3OCH1SRC_MASK | SIM_SOPT8_FTM3OCH2SRC_MASK | SIM_SOPT8_FTM3OCH3SRC_MASK | SIM_SOPT8_FTM3OCH4SRC_MASK | SIM_SOPT8_FTM3OCH5SRC_MASK)))

         /* FTM3 channel 0 output source: FTM3_CH0 pin is output of FTM3 channel 0 output. */
         | SIM_SOPT8_FTM3OCH0SRC(SOPT8_FTM3OCH0SRC_FTM)

         /* FTM3 channel 1 output source: FTM3_CH1 pin is output of FTM3 channel 1 output. */
         | SIM_SOPT8_FTM3OCH1SRC(SOPT8_FTM3OCH1SRC_FTM)

         /* FTM3 channel 2 output source: FTM3_CH2 pin is output of FTM3 channel 2 output. */
         | SIM_SOPT8_FTM3OCH2SRC(SOPT8_FTM3OCH2SRC_FTM)

         /* FTM3 channel 3 output source: FTM3_CH3 pin is output of FTM3 channel 3 output. */
         | SIM_SOPT8_FTM3OCH3SRC(SOPT8_FTM3OCH3SRC_FTM)

         /* FTM3 channel 4 output source: FTM3_CH4 pin is output of FTM3 channel 4 output. */
         | SIM_SOPT8_FTM3OCH4SRC(SOPT8_FTM3OCH4SRC_FTM)

         /* FTM3 channel 5 output source: FTM3_CH5 pin is output of FTM3 channel 5 output. */
         | SIM_SOPT8_FTM3OCH5SRC(SOPT8_FTM3OCH5SRC_FTM));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_EMAG:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '18', peripheral: HSADC0, signal: 'ADCA, CH0', pin_signal: HSADC0A_CH0/ADC0_SE1/ADC0_DP1/PTE16/SPI0_PCS0/UART2_TX/FTM_CLKIN0/FTM0_FLT3}
  - {pin_num: '19', peripheral: HSADC0, signal: 'ADCA, CH1', pin_signal: HSADC0A_CH1/ADC0_SE9/ADC0_DM1/PTE17/LLWU_P19/SPI0_SCK/UART2_RX/FTM_CLKIN1/LPTMR0_ALT3}
  - {pin_num: '20', peripheral: HSADC0, signal: 'ADCB, CH0', pin_signal: HSADC0B_CH0/ADC0_SE5a/PTE18/LLWU_P20/SPI0_SOUT/UART2_CTS_b/I2C0_SDA}
  - {pin_num: '21', peripheral: HSADC0, signal: 'ADCB, CH1', pin_signal: HSADC0B_CH1/ADC0_SE6a/PTE19/SPI0_SIN/UART2_RTS_b/I2C0_SCL/CMP3_OUT}
  - {pin_num: '27', peripheral: HSADC1, signal: 'ADCA, CH2', pin_signal: HSADC0A_CH2/HSADC1A_CH2}
  - {pin_num: '28', peripheral: HSADC1, signal: 'ADCA, CH3', pin_signal: HSADC0A_CH3/HSADC1A_CH3}
  - {pin_num: '29', peripheral: HSADC1, signal: 'ADCB, CH2', pin_signal: HSADC0A_CH10/HSADC1B_CH2}
  - {pin_num: '30', peripheral: HSADC1, signal: 'ADCB, CH3', pin_signal: HSADC0A_CH11/HSADC1B_CH3}
  - {pin_num: '23', peripheral: HSADC0, signal: 'ADCA, CH6', pin_signal: HSADC0A_CH6/ADC0_SE7a}
  - {pin_num: '24', peripheral: HSADC0, signal: 'ADCA, CH7', pin_signal: HSADC0A_CH7/ADC0_SE4b}
  - {pin_num: '25', peripheral: HSADC0, signal: 'ADCA, CH8', pin_signal: HSADC0A_CH8/ADC0_SE5b/PTE20/FTM1_CH0/UART0_TX/FTM1_QD_PHA}
  - {pin_num: '26', peripheral: HSADC0, signal: 'ADCA, CH9', pin_signal: HSADC0A_CH9/HSADC1A_CH7/PTE21/XB_IN9/FTM1_CH1/UART0_RX/FTM1_QD_PHB}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_EMAG
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_EMAG(void)
{
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTE16 (pin 18) is configured as HSADC0A_CH0 */
    PORT_SetPinMux(RTEPIN_EMAG_EMAG_EWL_PORT, RTEPIN_EMAG_EMAG_EWL_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE17 (pin 19) is configured as HSADC0A_CH1 */
    PORT_SetPinMux(RTEPIN_EMAG_EMAG_EXL_PORT, RTEPIN_EMAG_EMAG_EXL_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE18 (pin 20) is configured as HSADC0B_CH0 */
    PORT_SetPinMux(RTEPIN_EMAG_EMAG_EWR_PORT, RTEPIN_EMAG_EMAG_EWR_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE19 (pin 21) is configured as HSADC0B_CH1 */
    PORT_SetPinMux(RTEPIN_EMAG_EMAG_EXR_PORT, RTEPIN_EMAG_EMAG_EXR_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE20 (pin 25) is configured as HSADC0A_CH8 */
    PORT_SetPinMux(RTEPIN_EMAG_EMAG_EYR_PORT, RTEPIN_EMAG_EMAG_EYR_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTE21 (pin 26) is configured as HSADC0A_CH9 */
    PORT_SetPinMux(RTEPIN_EMAG_EMAG_EZR_PORT, RTEPIN_EMAG_EMAG_EZR_PIN, kPORT_PinDisabledOrAnalog);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Debug:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '51', peripheral: UART0, signal: RX, pin_signal: PTA1/UART0_RX/FTM0_CH6/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/JTAG_TDI, pull_select: up, pull_enable: enable}
  - {pin_num: '52', peripheral: UART0, signal: TX, pin_signal: PTA2/UART0_TX/FTM0_CH7/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0/JTAG_TDO/TRACE_SWO, direction: OUTPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '50', peripheral: JTAG, signal: JTAG_TCLK_SWD_CLK, pin_signal: PTA0/UART0_CTS_b/UART0_COL_b/FTM0_CH5/XB_IN4/EWM_IN/JTAG_TCLK/SWD_CLK}
  - {pin_num: '53', peripheral: JTAG, signal: JTAG_TMS_SWD_DIO, pin_signal: PTA3/UART0_RTS_b/FTM0_CH0/XB_IN9/EWM_OUT_b/FLEXPWM0_A0/JTAG_TMS/SWD_DIO}
  - {pin_num: '74', peripheral: RCM, signal: RESET, pin_signal: RESET_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Debug
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Debug(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);

    /* PORTA0 (pin 50) is configured as JTAG_TCLK */
    PORT_SetPinMux(RTEPIN_DEBUG_DBG_TCK_PORT, RTEPIN_DEBUG_DBG_TCK_PIN, kPORT_MuxAlt7);

    /* PORTA1 (pin 51) is configured as UART0_RX */
    PORT_SetPinMux(RTEPIN_DEBUG_DBG_UART_RX_PORT, RTEPIN_DEBUG_DBG_UART_RX_PIN, kPORT_MuxAlt2);

    PORTA->PCR[1] = ((PORTA->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTA2 (pin 52) is configured as UART0_TX */
    PORT_SetPinMux(RTEPIN_DEBUG_DBG_UART_TX_PORT, RTEPIN_DEBUG_DBG_UART_TX_PIN, kPORT_MuxAlt2);

    PORTA->PCR[2] = ((PORTA->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTA3 (pin 53) is configured as JTAG_TMS */
    PORT_SetPinMux(RTEPIN_DEBUG_DBT_TMS_PORT, RTEPIN_DEBUG_DBT_TMS_PIN, kPORT_MuxAlt7);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

                  /* UART 0 receive data source select: UART0_RX pin. */
                  | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_TofSensor:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '59', peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: HSADC1B_CH8/PTA7/FTM0_CH4/RMII0_MDIO/MII0_MDIO/TRACE_D3, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '60', peripheral: GPIOA, signal: 'GPIO, 8', pin_signal: HSADC1B_CH9/PTA8/FTM1_CH0/RMII0_MDC/MII0_MDC/TRACE_D2, direction: INPUT}
  - {pin_num: '61', peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/TRACE_D1, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '62', peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: PTA10/LLWU_P22/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0, direction: INPUT}
  - {pin_num: '63', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTA11/LLWU_P23/FTM2_CH1/MII0_RXCLK/FTM2_QD_PHB/I2C0_SDA, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '64', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/RMII0_RXD1/MII0_RXD1/FTM1_QD_PHA/I2C0_SCL, direction: INPUT}
  - {pin_num: '65', peripheral: I2C1, signal: SDA, pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/RMII0_RXD0/MII0_RXD0/FTM1_QD_PHB/I2C1_SDA, open_drain: enable,
    pull_select: up, pull_enable: enable}
  - {pin_num: '66', peripheral: I2C1, signal: SCL, pin_signal: CMP3_IN0/PTA14/SPI0_PCS0/UART0_TX/CAN2_TX/RMII0_CRS_DV/MII0_RXDV/I2C1_SCL, open_drain: enable, pull_select: up,
    pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_TofSensor
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_TofSensor(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);

    gpio_pin_config_t TOF0_XHT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA7 (pin 59)  */
    GPIO_PinInit(RTEPIN_TOFSENSOR_TOF0_XHT_GPIO, RTEPIN_TOFSENSOR_TOF0_XHT_PIN, &TOF0_XHT_config);

    gpio_pin_config_t TOF0_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA8 (pin 60)  */
    GPIO_PinInit(RTEPIN_TOFSENSOR_TOF0_INT_GPIO, RTEPIN_TOFSENSOR_TOF0_INT_PIN, &TOF0_INT_config);

    gpio_pin_config_t TOF1_XHT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA9 (pin 61)  */
    GPIO_PinInit(RTEPIN_TOFSENSOR_TOF1_XHT_GPIO, RTEPIN_TOFSENSOR_TOF1_XHT_PIN, &TOF1_XHT_config);

    gpio_pin_config_t TOF1_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA10 (pin 62)  */
    GPIO_PinInit(RTEPIN_TOFSENSOR_TOF1_INT_GPIO, RTEPIN_TOFSENSOR_TOF1_INT_PIN, &TOF1_INT_config);

    gpio_pin_config_t TOF2_XHT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA11 (pin 63)  */
    GPIO_PinInit(RTEPIN_TOFSENSOR_TOF2_XHT_GPIO, RTEPIN_TOFSENSOR_TOF2_XHT_PIN, &TOF2_XHT_config);

    gpio_pin_config_t TOF2_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA12 (pin 64)  */
    GPIO_PinInit(RTEPIN_TOFSENSOR_TOF2_INT_GPIO, RTEPIN_TOFSENSOR_TOF2_INT_PIN, &TOF2_INT_config);

    /* PORTA10 (pin 62) is configured as PTA10 */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOF1_INT_PORT, RTEPIN_TOFSENSOR_TOF1_INT_PIN, kPORT_MuxAsGpio);

    /* PORTA11 (pin 63) is configured as PTA11 */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOF2_XHT_PORT, RTEPIN_TOFSENSOR_TOF2_XHT_PIN, kPORT_MuxAsGpio);

    /* PORTA12 (pin 64) is configured as PTA12 */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOF2_INT_PORT, RTEPIN_TOFSENSOR_TOF2_INT_PIN, kPORT_MuxAsGpio);

    /* PORTA13 (pin 65) is configured as I2C1_SDA */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOFn_SDA_PORT, RTEPIN_TOFSENSOR_TOFn_SDA_PIN, kPORT_MuxAlt8);

    PORTA->PCR[13] = ((PORTA->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTA14 (pin 66) is configured as I2C1_SCL */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOFn_SCL_PORT, RTEPIN_TOFSENSOR_TOFn_SCL_PIN, kPORT_MuxAlt8);

    PORTA->PCR[14] = ((PORTA->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTA7 (pin 59) is configured as PTA7 */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOF0_XHT_PORT, RTEPIN_TOFSENSOR_TOF0_XHT_PIN, kPORT_MuxAsGpio);

    /* PORTA8 (pin 60) is configured as PTA8 */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOF0_INT_PORT, RTEPIN_TOFSENSOR_TOF0_INT_PIN, kPORT_MuxAsGpio);

    /* PORTA9 (pin 61) is configured as PTA9 */
    PORT_SetPinMux(RTEPIN_TOFSENSOR_TOF1_XHT_PORT, RTEPIN_TOFSENSOR_TOF1_XHT_PIN, kPORT_MuxAsGpio);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_ImuTcsSensor:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '79', peripheral: GPIOA, signal: 'GPIO, 28', pin_signal: PTA28/MII0_TXER/FB_A25, direction: INPUT}
  - {pin_num: '80', peripheral: GPIOA, signal: 'GPIO, 29', pin_signal: PTA29/MII0_COL/FB_A24, direction: INPUT}
  - {pin_num: '81', peripheral: I2C0, signal: SCL, pin_signal: HSADC0B_CH2/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX/RMII0_MDIO/MII0_MDIO, identifier: IMU_SCL,
    open_drain: enable, drive_strength: high, pull_select: up, pull_enable: enable}
  - {pin_num: '82', peripheral: I2C0, signal: SDA, pin_signal: HSADC0B_CH3/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX/RMII0_MDC/MII0_MDC, identifier: IMU_SDA,
    open_drain: enable, drive_strength: high, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_ImuTcsSensor
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_ImuTcsSensor(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    gpio_pin_config_t TCS_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA28 (pin 79)  */
    GPIO_PinInit(RTEPIN_IMUTCSSENSOR_TCS_INT_GPIO, RTEPIN_IMUTCSSENSOR_TCS_INT_PIN, &TCS_INT_config);

    gpio_pin_config_t IMU_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA29 (pin 80)  */
    GPIO_PinInit(RTEPIN_IMUTCSSENSOR_IMU_INT_GPIO, RTEPIN_IMUTCSSENSOR_IMU_INT_PIN, &IMU_INT_config);

    /* PORTA28 (pin 79) is configured as PTA28 */
    PORT_SetPinMux(RTEPIN_IMUTCSSENSOR_TCS_INT_PORT, RTEPIN_IMUTCSSENSOR_TCS_INT_PIN, kPORT_MuxAsGpio);

    /* PORTA29 (pin 80) is configured as PTA29 */
    PORT_SetPinMux(RTEPIN_IMUTCSSENSOR_IMU_INT_PORT, RTEPIN_IMUTCSSENSOR_IMU_INT_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 81) is configured as I2C0_SCL */
    PORT_SetPinMux(RTEPIN_IMUTCSSENSOR_IMU_SCL_PORT, RTEPIN_IMUTCSSENSOR_IMU_SCL_PIN, kPORT_MuxAlt2);

    PORTB->PCR[0] =
        ((PORTB->PCR[0] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

         /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the corresponding PE
          * field is set. */
         | (uint32_t)(kPORT_PullUp)

         /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is configured as
          * a digital output. */
         | PORT_PCR_ODE(kPORT_OpenDrainEnable)

         /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin is
          * configured as a digital output. */
         | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTB1 (pin 82) is configured as I2C0_SDA */
    PORT_SetPinMux(RTEPIN_IMUTCSSENSOR_IMU_SDA_PORT, RTEPIN_IMUTCSSENSOR_IMU_SDA_PIN, kPORT_MuxAlt2);

    PORTB->PCR[1] =
        ((PORTB->PCR[1] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

         /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the corresponding PE
          * field is set. */
         | (uint32_t)(kPORT_PullUp)

         /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is configured as
          * a digital output. */
         | PORT_PCR_ODE(kPORT_OpenDrainEnable)

         /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin is
          * configured as a digital output. */
         | PORT_PCR_DSE(kPORT_HighDriveStrength));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_Switch:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '144', peripheral: GPIOD, signal: 'GPIO, 15', pin_signal: PTD15/SPI2_PCS1/FLEXPWM0_B0/FB_A23, direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '143', peripheral: GPIOD, signal: 'GPIO, 14', pin_signal: PTD14/SPI2_SIN/XB_IN11/XB_OUT11/FLEXPWM0_A0/FB_A22, direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '142', peripheral: GPIOD, signal: 'GPIO, 13', pin_signal: PTD13/SPI2_SOUT/XB_IN7/XB_OUT7/FLEXPWM0_B1/FB_A21, direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '141', peripheral: GPIOD, signal: 'GPIO, 12', pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/XB_IN5/XB_OUT5/FLEXPWM0_A1/FB_A20, direction: INPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '140', peripheral: GPIOD, signal: 'GPIO, 11', pin_signal: PTD11/LLWU_P25/SPI2_PCS0/UART5_CTS_b/FLEXPWM0_B2/FB_A19, direction: INPUT, pull_select: up,
    pull_enable: enable}
  - {pin_num: '139', peripheral: GPIOD, signal: 'GPIO, 10', pin_signal: PTD10/UART5_RTS_b/FLEXPWM0_A2/FB_A18, direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '138', peripheral: GPIOD, signal: 'GPIO, 9', pin_signal: PTD9/I2C1_SDA/UART5_TX/FLEXPWM0_B3/FB_A17, direction: INPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '137', peripheral: GPIOD, signal: 'GPIO, 8', pin_signal: PTD8/LLWU_P24/I2C1_SCL/UART5_RX/FLEXPWM0_A3/FB_A16, direction: INPUT, pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_Switch
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_Switch(void)
{
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    gpio_pin_config_t KEY_SW07_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD8 (pin 137)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW07_GPIO, RTEPIN_SWITCH_KEY_SW07_PIN, &KEY_SW07_config);

    gpio_pin_config_t KEY_SW00_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD9 (pin 138)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW00_GPIO, RTEPIN_SWITCH_KEY_SW00_PIN, &KEY_SW00_config);

    gpio_pin_config_t KEY_SW06_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD10 (pin 139)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW06_GPIO, RTEPIN_SWITCH_KEY_SW06_PIN, &KEY_SW06_config);

    gpio_pin_config_t KEY_SW01_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD11 (pin 140)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW01_GPIO, RTEPIN_SWITCH_KEY_SW01_PIN, &KEY_SW01_config);

    gpio_pin_config_t KEY_SW05_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD12 (pin 141)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW05_GPIO, RTEPIN_SWITCH_KEY_SW05_PIN, &KEY_SW05_config);

    gpio_pin_config_t KEY_SW02_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD13 (pin 142)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW02_GPIO, RTEPIN_SWITCH_KEY_SW02_PIN, &KEY_SW02_config);

    gpio_pin_config_t KEY_SW04_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD14 (pin 143)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW04_GPIO, RTEPIN_SWITCH_KEY_SW04_PIN, &KEY_SW04_config);

    gpio_pin_config_t KEY_SW03_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD15 (pin 144)  */
    GPIO_PinInit(RTEPIN_SWITCH_KEY_SW03_GPIO, RTEPIN_SWITCH_KEY_SW03_PIN, &KEY_SW03_config);

    /* PORTD10 (pin 139) is configured as PTD10 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW06_PORT, RTEPIN_SWITCH_KEY_SW06_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[10] = ((PORTD->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTD11 (pin 140) is configured as PTD11 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW01_PORT, RTEPIN_SWITCH_KEY_SW01_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[11] = ((PORTD->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTD12 (pin 141) is configured as PTD12 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW05_PORT, RTEPIN_SWITCH_KEY_SW05_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[12] = ((PORTD->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTD13 (pin 142) is configured as PTD13 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW02_PORT, RTEPIN_SWITCH_KEY_SW02_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[13] = ((PORTD->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTD14 (pin 143) is configured as PTD14 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW04_PORT, RTEPIN_SWITCH_KEY_SW04_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[14] = ((PORTD->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTD15 (pin 144) is configured as PTD15 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW03_PORT, RTEPIN_SWITCH_KEY_SW03_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[15] = ((PORTD->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTD8 (pin 137) is configured as PTD8 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW07_PORT, RTEPIN_SWITCH_KEY_SW07_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[8] = ((PORTD->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTD9 (pin 138) is configured as PTD9 */
    PORT_SetPinMux(RTEPIN_SWITCH_KEY_SW00_PORT, RTEPIN_SWITCH_KEY_SW00_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[9] = ((PORTD->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RTEPIN_AuxUart:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '119', peripheral: UART4, signal: RX, pin_signal: PTC14/I2C1_SCL/I2C0_SCL/FLEXPWM1_A0/FB_AD25/UART4_RX, pull_select: up, pull_enable: enable}
  - {pin_num: '120', peripheral: UART4, signal: TX, pin_signal: PTC15/I2C1_SDA/I2C0_SDA/FLEXPWM1_B0/FB_AD24/UART4_TX, direction: OUTPUT, pull_select: up, pull_enable: enable}
  - {pin_num: '123', peripheral: UART3, signal: RX, pin_signal: PTC16/CAN1_RX/UART3_RX/ENET0_1588_TMR0/FLEXPWM1_A2/FB_CS5_b/FB_TSIZ1/FB_BE23_16_b, pull_select: up,
    pull_enable: enable}
  - {pin_num: '124', peripheral: UART3, signal: TX, pin_signal: PTC17/CAN1_TX/UART3_TX/ENET0_1588_TMR1/FLEXPWM1_B2/FB_CS4_b/FB_TSIZ0/FB_BE31_24_b, direction: OUTPUT,
    pull_select: up, pull_enable: enable}
  - {pin_num: '129', peripheral: UART2, signal: RX, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FTM0_CH2/FLEXPWM0_A1/I2C0_SCL/FB_AD4/FLEXPWM1_A1, pull_select: up,
    pull_enable: enable}
  - {pin_num: '130', peripheral: UART2, signal: TX, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FTM0_CH3/FLEXPWM0_B1/I2C0_SDA/FB_AD3/FLEXPWM1_B1, direction: OUTPUT,
    pull_select: up, pull_enable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RTEPIN_AuxUart
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void RTEPIN_AuxUart(void)
{
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    /* PORTC14 (pin 119) is configured as UART4_RX */
    PORT_SetPinMux(RTEPIN_AUXUART_AUX_UART4_RX_PORT, RTEPIN_AUXUART_AUX_UART4_RX_PIN, kPORT_MuxAlt9);

    PORTC->PCR[14] = ((PORTC->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTC15 (pin 120) is configured as UART4_TX */
    PORT_SetPinMux(RTEPIN_AUXUART_AUX_UART4_TX_PORT, RTEPIN_AUXUART_AUX_UART4_TX_PIN, kPORT_MuxAlt9);

    PORTC->PCR[15] = ((PORTC->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTC16 (pin 123) is configured as UART3_RX */
    PORT_SetPinMux(RTEPIN_AUXUART_AUX_UART3_RX_PORT, RTEPIN_AUXUART_AUX_UART3_RX_PIN, kPORT_MuxAlt3);

    PORTC->PCR[16] = ((PORTC->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTC17 (pin 124) is configured as UART3_TX */
    PORT_SetPinMux(RTEPIN_AUXUART_AUX_UART3_TX_PORT, RTEPIN_AUXUART_AUX_UART3_TX_PIN, kPORT_MuxAlt3);

    PORTC->PCR[17] = ((PORTC->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp));

    /* PORTD2 (pin 129) is configured as UART2_RX */
    PORT_SetPinMux(RTEPIN_AUXUART_AUX_UART2_RX_PORT, RTEPIN_AUXUART_AUX_UART2_RX_PIN, kPORT_MuxAlt3);

    PORTD->PCR[2] = ((PORTD->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));

    /* PORTD3 (pin 130) is configured as UART2_TX */
    PORT_SetPinMux(RTEPIN_AUXUART_AUX_UART2_TX_PORT, RTEPIN_AUXUART_AUX_UART2_TX_PIN, kPORT_MuxAlt3);

    PORTD->PCR[3] = ((PORTD->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullUp));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
